school/register/urls.py
from atexit import register
from django.urls import path
from register import views
from register.views import ThanksTemplateView, TeacherCreateView, TeacherListview, TeacherDetailview, TeacherUpdateView, TeacherDeleteView


app_name = 'register'

urlpatterns = [
    path('', views.home_views, name = 'home'),
    path('thank_you/', ThanksTemplateView.as_view(), name = 'thanks'),
    path('teacher-form/', TeacherCreateView.as_view(), name = 'teacher_form'),
    path('teacher-list/', TeacherListview.as_view(), name = 'teacher_list'),
    path('register/teacher-detail/<int:pk>', TeacherDetailview.as_view(), name = 'detail_list'),
    path('register/teacher-update/<int:pk>', TeacherUpdateView.as_view(), name = 'update_list'),
    path('register/delete-teacher/<int:pk>', TeacherDeleteView.as_view(), name = 'delete_list'),
]

school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
]

school/register/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    subject = models.CharField(max_length=100)

    def __str__(self):
       return f"{self.first_name} {self.last_name} teaches {self.subject}"

school/register/views.py
from dataclasses import field
from django.shortcuts import render
from django.urls import reverse_lazy
from register.models import Teacher
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView

# Create your views here.
def home_views(request):
    return render(request, "home.html")

class ThanksTemplateView(TemplateView):
    template_name ="thank_you.html"


class TeacherCreateView(CreateView):
    model = Teacher
    fields = '__all__'
    success_url = reverse_lazy('register:thanks')


class TeacherListview(ListView):
    model = Teacher
    context_object_name = "teacher_list"

class TeacherDetailview(DetailView):
    model = Teacher    


class TeacherUpdateView(UpdateView):
    model = Teacher
    fields = '__all__'
    success_url = reverse_lazy('register:teacher_list')


class TeacherDeleteView(DeleteView):
    model = Teacher
    success_url = reverse_lazy('register:teacher_list')

school/register/templates/home.html
<h1>Vani School Pvt Ltd</h1><ul>
<li><a href="{% url 'register:teacher_form' %}">Register Teacher</a></li>
<li><a href="{% url 'register:teacher_list' %}">List Teacher</a></li>
</ul>

school/register/templates/register/teacher_confirm_delete.html
<h1>Are You Sure Want To Delete This Teacher</h1>
{{teacher}}
<form method = "POST">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>

school/register/templates/register/teacher_detail.html
<h1>Detail of Teacher</h1>
{{teacher}}

school/register/templates/register/teacher_form.html
<h1>Teacher Form</h1>
<form method ="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">
</form>

school/register/templates/register/teacher_list.html
<h1>Teacher list</h1>
<div>
    {% for teacher in teacher_list  %}
    <li><a href="/register/teacher-detail/{{teacher.id}}">{{teacher.first_name}} {{teacher.last_name}}</a></li> <ul>
        <li><a href="/register/teacher-update/{{teacher.id}}">Update {{teacher.first_name}}</a></li>
        <li><a href="/register/delete-teacher/{{teacher.id}}">Delete {{teacher.first_name}}</a></li>
        
    </ul>
    {% endfor %}
</div>

school/register/templates/thank_you.html
<h1>Thank you</h1>